services:
    nginx:
      image: nginx:alpine
      container_name: dev-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 80:80
    php-fpm:
      build: docker/php-fpm
      container_name: dev-php-fpm
      working_dir: /application
      volumes:
        - .:/application
    database:
      image: mariadb:latest
      container_name: dev-database
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        MYSQL_DATABASE: ${DB_DATABASE:-dev}
      ports:
        - ${DB_PORT:-3306}:3306